---
title: "Estimação VAR"
output: pdf_document
---

```{r, echo = F, include = T}

suppressMessages(library(tidyverse))

series <-
  read.csv("../dados/series_economicas_log.csv") %>%
  # read.csv("../dados/series_economicas_log_sem_ihh.csv") %>%
  dplyr::select(-date) %>%
  mutate_at(vars(spread, selic, inad), function(x) x - lag(x)) %>%
  na.omit()

# tornando a série do pib_mensal estacionária
series$pib_mensal <-
  lm(pib_mensal ~ seq_along(pib_mensal), data = series)$residuals

```

```{r, echo = F, include = T}

library(lmtest)

lmtest::grangertest(spread ~ inad, data = series, order = 1)

```

```{r, echo = F, include = T}

suppressMessages(library(vars))

VARselect(series, lag.max = 5, type = "const")

VAR(y = series %>% dplyr::select(spread, selic, inad, pib_mensal, ihh),
    # exogen = series %>% dplyr::select(igp, ihh),
    p = 1, type = "const") -> var_model

var_model %>% summary
var_model %>% roots

# irf(var_model,
#     response = "spread",
#     # cumulative = T,
#     n.ahead = 12, ortho = F) %>% plot

```

```{r, echo = F, include = T}

urca::ca.jo(series) %>% summary

```
