---
title: "Testes de raiz unitária"
output: pdf_document
---

```{r, include = F, echo = FALSE}

knitr::opts_chunk$set(comment = NA, warning = FALSE, message = FALSE)

library(tidyverse)
library(tseries)

series <- read_csv("~/Documentos/mono/dados/series_economicas.csv")
```

```{r, echo = F}

# definir funções para retornar o p-valor do teste
adf <- function(x) { adf.test(x) %>% unlist() %>% `[`(4) }
pp <- function(x) { pp.test(x) %>% unlist() %>% `[`(4) }
kpss <- function(x) { kpss.test(x) %>% unlist() %>% `[`(3) }
 
library(ggrepel)
library(scales)
theme_set(theme_minimal())

unit_root_tests <- series %>%
  summarise_at(vars(-date), list(adf = adf, pp = pp, kpss = kpss)) %>%
  gather(value = "pvalor") %>%
  extract(key, into = c("variavel", "teste"), regex = "([a-z_]+)_(.+$)") %>%
  mutate(
    diagnostico = case_when(
      teste != "kpss" ~ ifelse(pvalor < .05, "estacionário", "não-estacionário"),
      teste == "kpss" ~ ifelse(pvalor > .05, "estacionário", "não-estacionário")
    ), pvalor = as.numeric(pvalor)
  )

unit_root_tests %>%
  ggplot(aes(teste, variavel, fill = diagnostico)) +
  geom_tile() +
  geom_text(aes(label = pvalor %>% round(2))) +
  labs(
    x = NULL, y = NULL,
    title = "Resultados dos testes de raiz unitária para cada variável",
    caption = "Hipótese nula de raiz unitária, exceto para KPSS"
  ) +
  theme(legend.position = "bottom") +
  scale_fill_manual(values = c("azure3", "lightgrey")) +
  scale_x_discrete(labels = c(
    "Augmented\nDickey-Fuller",
    "KPSS",
    "Phillips-Perron"
  ))

```

\newpage
\begin{center}\LARGE{Séries diagnosticadas como estacionárias em cada teste}\end{center}

```{r, echo = F}

series_unit_root <- series %>%
  gather(key = "variavel", value = "value", -date) %>%
  right_join(unit_root_tests, by = c(variavel = "variavel"))

plotar_series_estacionarias <- function(x) {
  series_unit_root %>%
    filter(diagnostico == "estacionário", teste == x) %>%
    ggplot(aes(date, value)) +
    geom_smooth(method = "lm", se = FALSE) +
    geom_line(size = .5) +
    theme(legend.position = "none") +
    labs(x = NULL, y = NULL) +
    facet_wrap(teste ~ variavel,
      scales = "free",
      nrow = 3, ncol = 7
    )
}

library(gridExtra)
grid.arrange(
  plotar_series_estacionarias("adf"),
  plotar_series_estacionarias("pp"),
  plotar_series_estacionarias("kpss")
)

```

\newpage
\large{Sem drift e sem tendência linear}

```{r, echo = F}

sapply(series %>% select(-date),
       function(x) aTSA::adf.test(x, output=F)[1])

```


\newpage
\large{Com drift e sem tendência linear}

```{r, echo = F}

sapply(series %>% select(-date),
       function(x) aTSA::adf.test(x, output=F)[2])

```

\newpage
\large{Com drift e com tendência linear}

```{r, echo = F}

sapply(series %>% select(-date),
       function(x) aTSA::adf.test(x, output=F)[3])

```
